Autocomplete bugfix
CS2103AUG2017-T16-B1/main pull request #180
Opened 2017-11-08 18:26 UTC by Kowalski985

fixed some bugs I found in the current version of the autocompleter:
 - Some prefixes are missed out when cycling through the list of missing prefixes after deleting some prefixes that had previously been keyed into the command box
 - Edit command autocomplete will see any argument without a prefix as an index even if it is not a number
 - first letters of prefixes are not recognized

2017-11-08 19:09 UTC, Kowalski985 commented
Drop in coverage to due to exception catching which can't be tested

2017-11-09 03:15 UTC, Kennard123661 requested changes

2017-11-09 03:15 UTC, Kennard123661 commented on src/test/java/seedu/address/ui/AutocompleterTest.java
> +
get rid of these newlines lol

2017-11-09 03:15 UTC, Kennard123661 commented on src/main/java/seedu/address/ui/CommandBoxParser.java
> +                missingPrefixes.add(p.toString());
this is starting to look like arrow head code

2017-11-09 03:43 UTC, Kennard123661 approved these changes

2017-11-09 03:52 UTC, merged